services:
  # Backend API Service
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: movie-backend
    ports:
      - "8000:8000"
    environment:
      - DATABASE_URL=sqlite:///database/local/database.sqlite
      - ENVIRONMENT=production
      - LOG_LEVEL=INFO
    volumes:
      - ./backend/database:/app/database
      - ./backend/logs:/app/logs
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    restart: unless-stopped
    networks:
      - movie-network

  # Frontend Web Service  
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: movie-frontend
    ports:
      - "3000:3000"
    environment:
      - NEXT_PUBLIC_API_URL=http://localhost:8000
      - NODE_ENV=production
    depends_on:
      backend:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3000/api/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    restart: unless-stopped
    networks:
      - movie-network

networks:
  movie-network:
    driver: bridge

volumes:
  movie-data:
    driver: local
